name: Reachability Checker

# Controls when the workflow will run
on:
  issues:
    # 新增（打开）/编辑/关闭/重新打开/设置标签/移除标签
    types: [opened, edited, closed, reopened, labeled, unlabeled]
  # 手动触发
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  reachability-checker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # 检查链接状态
      - name: Check Reachability
        uses: xaoxuu/links-checker@main
        with: # 全部可选
          checker: 'reachability' # theme: 主题检查， reachability: 链接可访问性检查
          exclude_issue_with_labels: '审核中, 白名单, 缺少互动, 缺少文章' # 具有哪些标签的issue不进行检查
          retry_times: 3 # 重试几次
          accepted_codes: '200,201,202,203,204,205,206,300,301,302,303,304,307,308' # 哪些状态码可以接受（认为可访问）
          unreachable_label: '无法访问' # 不能访问时，会贴上什么标签

      ... 接下来调用 issues2json 再生成一次数据
